package com.example.ui.localization

object StringsManager {
    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.URDU) urduStrings else englishStrings
        return dict[key] ?: englishStrings[key] ?: key
    }

    private val englishStrings = mapOf(
        // App header & general
        "app_name" to "Sarmaya Invest",
        "app_tagline" to "Smart Online Earning & Investment Platform",
        "home" to "Home",
        "plans" to "Plans",
        "active_plans" to "My Portfolio",
        "wallet" to "Wallet",
        "rewards" to "Daily Tasks",
        "referrals" to "Affiliates",
        "history" to "History",
        "support" to "Help Center",
        "profile" to "Profile",
        
        // Dashboard
        "total_balance" to "Total Balance",
        "active_invested" to "Active Invested",
        "total_profit" to "Total Profit",
        "referral_bonus" to "Affiliate Bonus",
        "todays_profit" to "Today's Profit",
        "quick_actions" to "Quick Actions",
        "deposit" to "Deposit",
        "withdraw" to "Withdraw",
        "invest_now" to "Invest Now",
        "calculator" to "Calculator",
        "claim_profit" to "Claim Daily ROI",
        "profit_claimed" to "Daily profit successfully claimed!",
        "next_payout_in" to "Next Payout In",
        "vip_member" to "VIP Verified Member",
        "kyc_verified" to "KYC Verified",
        "kyc_pending" to "Verify KYC",
        
        // Plans
        "investment_plans" to "Investment Plans",
        "plans_subtitle" to "Choose high-yield automated daily return packages",
        "daily_roi" to "Daily ROI",
        "duration" to "Duration",
        "min_deposit" to "Min Deposit",
        "max_deposit" to "Max Deposit",
        "total_return" to "Total Return",
        "capital_back" to "Principal Back",
        "yes" to "Yes",
        "no" to "No",
        "days" to "Days",
        "instant_payout" to "Instant Daily Payout",
        "choose_plan" to "Select Plan",
        "popular" to "Most Popular",
        "high_yield" to "High Yield",
        "starter_pack" to "Best for Starters",
        "vip_exclusive" to "VIP Exclusive",
        "risk_level" to "Risk Level",
        "low_risk" to "Low Risk",
        "moderate_risk" to "Moderate Risk",
        "high_growth" to "High Growth",
        
        // Calculator
        "profit_calculator" to "Profit Calculator",
        "calc_desc" to "Calculate your estimated daily and total net earnings",
        "enter_amount" to "Enter Investment Amount",
        "select_plan" to "Select Plan",
        "daily_profit" to "Daily Return",
        "weekly_profit" to "Weekly Return",
        "total_net_profit" to "Total Net Profit",
        "total_payout" to "Total Payout",
        "roi_percentage" to "Total ROI",
        
        // Deposit
        "deposit_funds" to "Deposit Funds",
        "deposit_desc" to "Add money via JazzCash, EasyPaisa, Bank Transfer or USDT",
        "payment_method" to "Payment Method",
        "account_title" to "Account Title",
        "account_number" to "Account / IBAN Number",
        "copy" to "Copy",
        "copied" to "Copied to clipboard!",
        "transaction_id" to "Transaction ID (TID / Hash)",
        "enter_tid" to "Enter 10-12 digit Transaction ID",
        "deposit_instructions" to "1. Send exact amount to the account above.\n2. Copy Transaction ID (TID) from SMS/App.\n3. Paste TID below and click Submit.",
        "submit_deposit" to "Submit Deposit Request",
        "deposit_success_msg" to "Deposit request submitted! Balance will update automatically.",
        "min_deposit_error" to "Minimum deposit amount is 500 PKR ($5)",
        
        // Withdraw
        "withdraw_funds" to "Withdraw Funds",
        "withdraw_desc" to "Instant withdrawal to your local bank or mobile wallet",
        "available_balance" to "Available Balance",
        "withdraw_amount" to "Withdrawal Amount",
        "payout_account" to "Account / Wallet Number",
        "account_holder" to "Account Holder Name",
        "withdrawal_fee" to "Processing Fee (0%)",
        "net_payout" to "Net Amount Received",
        "submit_withdraw" to "Request Withdrawal",
        "withdraw_success_msg" to "Withdrawal request submitted! Funds will arrive in 5-15 minutes.",
        "min_withdraw_error" to "Minimum withdrawal is 200 PKR ($2)",
        "insufficient_balance" to "Insufficient balance!",
        
        // Referral
        "referral_program" to "Affiliate Program",
        "referral_desc" to "Invite friends & earn up to 3 Levels of passive commissions!",
        "your_referral_code" to "Your Invite Code",
        "your_referral_link" to "Your Referral Link",
        "copy_code" to "Copy Code",
        "copy_link" to "Copy Link",
        "share_whatsapp" to "Share on WhatsApp",
        "tier_1" to "Level 1 (Direct)",
        "tier_2" to "Level 2 (Team)",
        "tier_3" to "Level 3 (Network)",
        "commission" to "Commission",
        "total_invited" to "Total Referrals",
        "active_team" to "Active Investors",
        "total_commission" to "Total Commission",
        "team_list" to "Team Members",
        
        // Tasks & Rewards
        "daily_tasks_title" to "Daily Tasks & Rewards",
        "tasks_desc" to "Earn extra bonus cash every day without investment",
        "daily_checkin" to "Daily Check-In",
        "checkin_btn" to "Claim Today's Bonus",
        "claimed" to "Claimed",
        "day" to "Day",
        "lucky_spin" to "Lucky Spin Wheel",
        "spin_desc" to "Spin the wheel to win instant cash up to 1,000 PKR",
        "spin_now" to "Spin Now",
        "spins_left" to "Free Spins Available",
        "watch_ad" to "Watch Sponsor Video",
        "watch_ad_desc" to "Watch 15-sec promotional video and get 25 PKR",
        "join_telegram" to "Join Official Telegram",
        "join_whatsapp" to "Join WhatsApp Channel",
        "daily_quiz" to "Daily Financial Quiz",
        "task_reward_claimed" to "Task Reward Added to Wallet!",
        
        // Portfolio / Active Investments
        "my_investments" to "Active Investments",
        "no_active_investments" to "You have no active investment plans yet.",
        "explore_plans" to "Explore Plans & Start Earning",
        "progress" to "Maturity Progress",
        "daily_return_rate" to "Daily Return Rate",
        "earned_so_far" to "Earned So Far",
        "total_target" to "Total Target",
        "days_left" to "Days Remaining",
        "active_status" to "Active & Earning",
        "completed_status" to "Matured / Completed",
        
        // Transactions
        "transaction_history" to "Transaction History",
        "filter_all" to "All",
        "filter_deposit" to "Deposits",
        "filter_withdraw" to "Withdrawals",
        "filter_profit" to "ROI Profits",
        "filter_bonus" to "Bonuses",
        "completed" to "Completed",
        "pending" to "Pending",
        "failed" to "Failed",
        "view_receipt" to "View Receipt",
        
        // Support
        "customer_support" to "Help & Support Center",
        "support_desc" to "24/7 Live Agent Support & Official Communities",
        "live_chat" to "Live Chat Support",
        "faq_title" to "Frequently Asked Questions",
        "community_links" to "Official Social Groups",
        "telegram_community" to "Telegram Global Channel",
        "whatsapp_community" to "WhatsApp VIP Group",
        "ask_question" to "Type your message or question...",
        "send" to "Send",
        
        // Profile
        "user_profile" to "My Account",
        "member_id" to "User ID",
        "joined_date" to "Joined Date",
        "security_settings" to "Security Settings",
        "change_pin" to "Security PIN",
        "language_setting" to "Language / زبان",
        "currency_setting" to "Currency",
        "dark_mode" to "Dark Mode",
        "notifications" to "Push Notifications",
        "logout" to "Log Out",
        "terms" to "Terms & Financial Disclaimer",
        
        // Language Switcher
        "language_switcher_title" to "Select Language",
        "language_switcher_subtitle" to "Choose your preferred language for the whole application",
        "select_language" to "Select Language",
        "english_title" to "English",
        "english_subtitle" to "English (US / Global)",
        "urdu_title" to "اردو (Urdu)",
        "urdu_subtitle" to "Urdu - قومی زبان",
        "apply_language" to "Apply Language",
        "language_changed" to "Language changed successfully!",
        "switch_language" to "Switch Language",
        "quick_lang_toggle" to "Toggle Language"
    )

    private val urduStrings = mapOf(
        // App header & general
        "app_name" to "سرمایہ انویسٹ",
        "app_tagline" to "اسمارٹ آن لائن ارننگ اور انویسٹمنٹ پلیٹ فارم",
        "home" to "ہوم",
        "plans" to "پلانز",
        "active_plans" to "میرا پورٹ فولیو",
        "wallet" to "والیٹ",
        "rewards" to "ڈیلی ٹاسکس",
        "referrals" to "ٹیم اور ریفرل",
        "history" to "ہسٹری",
        "support" to "مدد و رہنمائی",
        "profile" to "پروفائل",
        
        // Dashboard
        "total_balance" to "کل بیلنس",
        "active_invested" to "فعال سرمایہ کاری",
        "total_profit" to "کل حاصل شدہ منافع",
        "referral_bonus" to "ریفرل کمیشن",
        "todays_profit" to "آج کا منافع",
        "quick_actions" to "فوری ایکشنز",
        "deposit" to "ڈپازٹ کریں",
        "withdraw" to "رقم نکلوائیں",
        "invest_now" to "انویسٹ کریں",
        "calculator" to "کیلکولیٹر",
        "claim_profit" to "روزانہ منافع وصول کریں",
        "profit_claimed" to "آج کا منافع کامیابی سے والیٹ میں شامل کر دیا گیا!",
        "next_payout_in" to "اگلا منافع وقت",
        "vip_member" to "وی آئی پی تصدیق شدہ ممبر",
        "kyc_verified" to "KYC تصدیق شدہ",
        "kyc_pending" to "شناخت تصدیق کریں",
        
        // Plans
        "investment_plans" to "انویسٹمنٹ پلانز",
        "plans_subtitle" to "روزانہ منافع دینے والے منافع بخش اور محفوظ پیکجز منتخب کریں",
        "daily_roi" to "روزانہ منافع",
        "duration" to "مدت",
        "min_deposit" to "کم از کم رقم",
        "max_deposit" to "زیادہ سے زیادہ رقم",
        "total_return" to "کل واپسی منافع",
        "capital_back" to "اصل رقم کی واپسی",
        "yes" to "جی ہاں",
        "no" to "نہیں",
        "days" to "دن",
        "instant_payout" to "فوری روزانہ منافع",
        "choose_plan" to "پلان منتخب کریں",
        "popular" to "سب سے مقبول",
        "high_yield" to "زیادہ منافع بخش",
        "starter_pack" to "نئے ممبرز کیلئے بہترین",
        "vip_exclusive" to "وی آئی پی پیکج",
        "risk_level" to "رسک لیول",
        "low_risk" to "محفوظ و کم رسک",
        "moderate_risk" to "درمیانہ رسک",
        "high_growth" to "تیز رفتار گروتھ",
        
        // Calculator
        "profit_calculator" to "منافع کیلکولیٹر",
        "calc_desc" to "اپنی مطلوبہ رقم کا روزانہ اور کل منافع خود چیک کریں",
        "enter_amount" to "انویسٹمنٹ کی رقم درج کریں",
        "select_plan" to "پلان منتخب کریں",
        "daily_profit" to "روزانہ منافع",
        "weekly_profit" to "ہفتہ وار منافع",
        "total_net_profit" to "کل خالص منافع",
        "total_payout" to "کل رقم مع اصل",
        "roi_percentage" to "کل واپسی فیصد",
        
        // Deposit
        "deposit_funds" to "رقم جمع کروائیں (ڈپازٹ)",
        "deposit_desc" to "جاز کیش، ایزی پیسہ، بینک اکاؤنٹ یا کرپٹو USDT سے ڈپازٹ کریں",
        "payment_method" to "ادائیگی کا طریقہ",
        "account_title" to "اکاؤنٹ ٹائٹل / نام",
        "account_number" to "اکاؤنٹ / آئی بین نمبر",
        "copy" to "کاپی کریں",
        "copied" to "نمبر کاپی ہو گیا!",
        "transaction_id" to "ٹرانزیکشن آئی ڈی (TID / TRID)",
        "enter_tid" to "ایزی پیسہ/جازکیش میسج سے TID درج کریں",
        "deposit_instructions" to "1. اوپر دیے گئے نمبر پر رقم بھیجیں۔\n2. میسج سے ٹرانزیکشن آئی ڈی (TID) کاپی کریں۔\n3. نیچے TID درج کر کے سبمٹ بٹن دبائیں۔",
        "submit_deposit" to "ڈپازٹ سبمٹ کریں",
        "deposit_success_msg" to "ڈپازٹ کی درخواست موصول ہوگئی! رقم جلد ہی آپ کے والیٹ میں شامل ہو جائے گی۔",
        "min_deposit_error" to "کم از کم ڈپازٹ رقم 500 روپے ($5) ہے",
        
        // Withdraw
        "withdraw_funds" to "رقم نکلوائیں (ودڈرا)",
        "withdraw_desc" to "اپنے ایزی پیسہ، جاز کیش یا بینک اکاؤنٹ میں فوری ادائیگی حاصل کریں",
        "available_balance" to "موجودہ والیٹ بیلنس",
        "withdraw_amount" to "نکلوانے کی رقم",
        "payout_account" to "اکاؤنٹ / موبائل نمبر",
        "account_holder" to "اکاؤنٹ ہولڈر کا نام",
        "withdrawal_fee" to "سروس فیس (0%)",
        "net_payout" to "خالص وصول ہونے والی رقم",
        "submit_withdraw" to "ودڈرا کی درخواست بھیجیں",
        "withdraw_success_msg" to "ودڈرا کی درخواست موصول ہوگئی! رقم 5 سے 15 منٹ میں اکاؤنٹ میں پہنچ جائے گی۔",
        "min_withdraw_error" to "کم از کم ودڈرا رقم 200 روپے ($2) ہے",
        "insufficient_balance" to "آپ کے پاس مطلوبہ بیلنس موجود نہیں ہے!",
        
        // Referral
        "referral_program" to "ٹیم اور ریفرل پروگرام",
        "referral_desc" to "دوستوں کو انوائٹ کریں اور 3 لیول تک مستقل کمیشن کمائیں!",
        "your_referral_code" to "آپ کا ریفرل کوڈ",
        "your_referral_link" to "آپ کا ریفرل لنک",
        "copy_code" to "کوڈ کاپی کریں",
        "copy_link" to "لنک کاپی کریں",
        "share_whatsapp" to "واٹس ایپ پر شیئر کریں",
        "tier_1" to "لیول 1 (براہ راست)",
        "tier_2" to "لیول 2 (ٹیم ممبرز)",
        "tier_3" to "لیول 3 (نیٹ ورک)",
        "commission" to "کمیشن ریٹ",
        "total_invited" to "کل مدعو ممبرز",
        "active_team" to "فعال انویسٹرز",
        "total_commission" to "کل کمیشن آمدنی",
        "team_list" to "میری ٹیم کی فہرست",
        
        // Tasks & Rewards
        "daily_tasks_title" to "روزانہ ٹاسک اور انعامات",
        "tasks_desc" to "بغیر انویسٹمنٹ کے ہر روز مفت بونس اور انعامات حاصل کریں",
        "daily_checkin" to "ڈیلی چیک اِن بونس",
        "checkin_btn" to "آج کا بونس حاصل کریں",
        "claimed" to "حاصل شدہ",
        "day" to "دن",
        "lucky_spin" to "لکی اسپن وہیل",
        "spin_desc" to "پہیہ گھمائیں اور 1000 روپے تک نقد انعام جیتیں",
        "spin_now" to "ابھی اسپن کریں",
        "spins_left" to "مفت اسپن دستیاب",
        "watch_ad" to "ویڈیو ایڈ دیکھیں",
        "watch_ad_desc" to "15 سیکنڈ کا ایڈ دیکھیں اور فوری 25 روپے کمائیں",
        "join_telegram" to "آفیشل ٹیلیگرام گروپ جوائن کریں",
        "join_whatsapp" to "آفیشل واٹس ایپ چینل جوائن کریں",
        "daily_quiz" to "روزانہ آسان کوئز",
        "task_reward_claimed" to "ٹاسک انعام والیٹ میں شامل کر دیا گیا!",
        
        // Portfolio / Active Investments
        "my_investments" to "میرے فعال انویسٹمنٹ پلانز",
        "no_active_investments" to "فی الحال آپ کا کوئی انویسٹمنٹ پلان ایکٹو نہیں ہے۔",
        "explore_plans" to "پلانز دیکھیں اور ارننگ شروع کریں",
        "progress" to "پلان کی تکمیل کا فیصد",
        "daily_return_rate" to "روزانہ منافع کی شرح",
        "earned_so_far" to "اب تک کمایا گیا منافع",
        "total_target" to "کل متوقع آمدنی",
        "days_left" to "باقی دن",
        "active_status" to "فعال اور جاری",
        "completed_status" to "مکمل شدہ",
        
        // Transactions
        "transaction_history" to "لین دین کی تاریخ (ہسٹری)",
        "filter_all" to "تمام",
        "filter_deposit" to "ڈپازٹ",
        "filter_withdraw" to "ودڈرا",
        "filter_profit" to "منافع جات",
        "filter_bonus" to "بونس",
        "completed" to "کامیاب",
        "pending" to "زیرِ تصدیق",
        "failed" to "مسترد",
        "view_receipt" to "رسید دیکھیں",
        
        // Support
        "customer_support" to "ہیلپ اور کسٹمر سپورٹ",
        "support_desc" to "24/7 لائیو ایجنٹ سپورٹ اور آفیشل کمیونٹی لنکس",
        "live_chat" to "لائیو چیٹ سپورٹ",
        "faq_title" to "اکثر پوچھے جانے والے سوالات (FAQ)",
        "community_links" to "آفیشل سوشل لنکس",
        "telegram_community" to "ٹیلیگرام چینل",
        "whatsapp_community" to "واٹس ایپ گروپ",
        "ask_question" to "اپنا سوال یا پیغام یہاں ٹائپ کریں...",
        "send" to "بھیجیں",
        
        // Profile
        "user_profile" to "میرا اکاؤنٹ پروفائل",
        "member_id" to "یوزر آئی ڈی",
        "joined_date" to "شامل ہونے کی تاریخ",
        "security_settings" to "سیکیورٹی سیٹنگز",
        "change_pin" to "سیکیورٹی پن تبدیل کریں",
        "language_setting" to "زبان تبدیل کریں / Language",
        "currency_setting" to "کرنسی (PKR / USD)",
        "dark_mode" to "ڈارک موڈ",
        "notifications" to "اطلاعات (Notifications)",
        "logout" to "لاگ آؤٹ",
        "terms" to "شرائط و ضوابط اور مالیاتی ڈس کلیمر",
        
        // Language Switcher
        "language_switcher_title" to "زبان منتخب کریں",
        "language_switcher_subtitle" to "تمام ایپلیکیشن کے لیے اپنی پسندیدہ زبان منتخب کریں",
        "select_language" to "زبان کا انتخاب کریں",
        "english_title" to "English (انگریزی)",
        "english_subtitle" to "انگلش زبان (بائیں سے دائیں)",
        "urdu_title" to "اردو (Urdu)",
        "urdu_subtitle" to "قومی زبان اردو (دائیں سے بائیں)",
        "apply_language" to "زبان لاگو کریں",
        "language_changed" to "زبان کامیابی سے تبدیل ہو گئی ہے!",
        "switch_language" to "زبان تبدیل کریں",
        "quick_lang_toggle" to "زبان بدلیں"
    )
}
